/**:
  ros__parameters:
    # TIAGo frames (adjust if your MoveIt config differs)
    use_sim_time: true
    base_frame: "base_footprint"
    ee_frame: "gripper_grasping_frame" # often the tip link for TIAGo's arm
    tf_timeout: 0.2
    execute_timeout: 15.0
    max_torso_joint_value: 0.35
    torso_joint_name: "torso_lift_joint"

    gripper_touch_links: #TODO figure out links
      - gripper_left_finger_link
      - gripper_right_finger_link

    # Planning groups present in most TIAGo MoveIt setups
    # If your SRDF exposes only "arm" (no torso), replace "arm_torso" with "arm".
    planning_groups: ["arm_torso", "gripper", "arm"]

    # --- Per-group configs ---
    arm_torso:
      planning_time: 15.0
      max_velocity_scaling_factor: 0.6
      max_acceleration_scaling_factor: 0.6
      planning_attempts: 10
      planner_id: "" # use planner defaults
      planning_pipeline_id: "ompl"

    gripper:
      planning_time: 5.0
      max_velocity_scaling_factor: 0.2
      max_acceleration_scaling_factor: 0.2
      planning_attempts: 10
      planner_id: ""
      planning_pipeline_id: "ompl"

    arm:
      planning_time: 12.0
      max_velocity_scaling_factor: 0.6
      max_acceleration_scaling_factor: 0.6
      planning_attempts: 10
      planner_id: ""
      planning_pipeline_id: "ompl"
